import React from 'react';
import {DOLITELISTFROM,DOLIITETELELISTPITURUCE} from './DOLITELISTstyle'


// DOLITE 영화 소개 시 사용할 이미지 슬라이더 
export function DOLITELIST() {
     return (
        <DOLITELISTFROM>
            <DOLIITETELELISTPITURUCE>1</DOLIITETELELISTPITURUCE>
            <DOLIITETELELISTPITURUCE>1</DOLIITETELELISTPITURUCE>
            <DOLIITETELELISTPITURUCE>1</DOLIITETELELISTPITURUCE>
            <DOLIITETELELISTPITURUCE>1</DOLIITETELELISTPITURUCE>
            <DOLIITETELELISTPITURUCE>1</DOLIITETELELISTPITURUCE>
        </DOLITELISTFROM>
     );
 }


 export default DOLITELIST;